### ISSUE TITLE
[Plugin Support] TrMenu v3 Gradient | TrMenu v3 颜色支持

### ISSUE THREAD

**Issue by XDerHpl** [tuanzisama/minecraft-color-gradient-generator#10]
![image](https://github.com/user-attachments/assets/b528ae13-6c2d-4167-91d3-4c99b965a630)

**Comment by XDerHpl** [comment]
建议添加如上所示的渐变格式，改格式更加简洁，方便调整

**Comment by tuanzisama** [comment]
TrMenu (同 TrChat) 插件的`渐变`语法与生成器`MiniMessage#Gradient (adventure-api)`相同，可选择使用此项进行生成。

The `Gradient` syntax of the TrMenu (same as TrChat) plugin is the same as the generator `MiniMessage#Gradient (adventure-api)`, and you can choose to use this to generate.
