### ISSUE TITLE
[Plugin Support] 添加ItemsAdder文字效果

### ISSUE THREAD

**Issue by mon030** [tuanzisama/minecraft-color-gradient-generator#4]
**Plugin description**
IA的文字特效
![image](https://1341925849-files.gitbook.io/~/files/v0/b/gitbook-legacy-files/o/assets%2F-M28TcKgSDvuFN510qye%2F-MlL8i6c68MqtctzLv80%2F-MlLAOKvRe4aT8SHOW9u%2Frw_chat.gif?alt=media&token=941b342a-d29c-4320-be48-7fbdf3350f82)

**Plugin link/wiki**
https://itemsadder.devs.beer/plugin-usage/text-effects-1.17+

**Comment by tuanzisama** [comment]
在查看了 `ItemsAdder` 的文档后，issue中的截图所描述的文字效果，是由该插件所处理的。

是否指的是 [Using text effects without the placeholders - ItemsAdder](https://itemsadder.devs.beer/plugin-usage/text-effects-1.17+#using-text-effects-without-the-placeholders) ，还请具体指出。

**Comment by mon030** [comment]
> 在查看了 `ItemsAdder` 的文档后，issue中的截图所描述的文字效果，是由该插件所处理的。
> 
> 是否指的是 [Using text effects without the placeholders - ItemsAdder](https://itemsadder.devs.beer/plugin-usage/text-effects-1.17+#using-text-effects-without-the-placeholders) ，还请具体指出。

指的就是`Using text effects without the placeholders`这一部分内容

**Comment by mon030** [comment]
当然也希望能添加ia提供的用法，
如当希望生成rainbow效果时，输出结果为`<r 输入的内容>`

**Comment by tuanzisama** [comment]
`<r 输入的内容>` 经过测试，无法在“输入的内容”内添加16进制颜色，其他文字效果同样。

ItemsAdder 提出的“Special colors”，经测试不存在与其他16进制颜色共同使用的情况。
``` 
Jump: #FFFFFB
&#FFFFFB&#08d9d6一些内容文字
&#08d9d6&#FFFFFB一些内容文字
```
![image](https://github.com/tuanzisama/minecraft-color-gradient-generator/assets/33369729/f6a4e0ca-9a0c-44c3-829b-c36d76662be3)

此项目 **无法适配** 这种由插件处理的文字效果行为。

如果认为有异议，烦请附上更多信息和已使用的例子。
