### ISSUE TITLE
非常好的项目，但是请问开源协议是什么？

### ISSUE THREAD

**Issue by Mystic-Stars** [tuanzisama/minecraft-color-gradient-generator#5]
如题，今天偶然在哔哩哔哩看到了这个项目，体验后感觉非常棒！也很实用，就想自己也弄个这玩意儿，但是看了您的存储库里没有标注许可证，所以请问作者大大本项目开源协议用的什么呢🤔
QAQ.

**Comment by tuanzisama** [comment]
`MIT License`，但希望能标注来源（可选）
