### ISSUE TITLE
添加Chat Colorsmod的支持

### ISSUE THREAD

**Issue by jiahuli** [tuanzisama/minecraft-color-gradient-generator#8]
Chat Colorsmod用的格式[#ff0000]red text

**Comment by tuanzisama** [comment]
请附上该Mod/插件的链接或文档。

Please write the link or document of the mod/plugin.

**Comment by tuanzisama** [comment]
> 请附上该Mod/插件的链接或文档。
> 
> Please write the link or document of the mod/plugin.

看你贴出的示例，应当是此Mod吧？
https://www.curseforge.com/minecraft/mc-mods/chat-colours

**Comment by jiahuli** [comment]
对的，是这个

**Comment by tuanzisama** [comment]
已经根据其文档进行适配，但现在我不方便测试。如果有时间你可以验证一下~
如果没问题我将合并至`v2`分支。

`feat/chat-colors`分支预览地址：https://minecraft-gradient-text-generator-arte3jzku.vercel.app/

**Comment by jiahuli** [comment]
可以使用~感谢制作

**Comment by tuanzisama** [comment]
好的，我合并到`v2`分支。
